
package entornos.programa4.ventanas;

import entornos.programa4.pinceles.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;

public class VentanaDibujo extends javax.swing.JFrame {
    
    
    //Lienzo de mi programa
    private BufferedImage lienzo;

    /**
     * Creates new form VentanaDibujo
     */
    public VentanaDibujo() {
        initComponents();
        cmdColor.setOpaque(true);
        cmdColor.setBorderPainted(false); // opcional
        cmdColor.setBackground(Color.BLACK); // color inicial
        //para poner el fondo donde pintamos en blanco
        lblAreaDibujo.setOpaque(true);
        lblAreaDibujo.setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbBotones = new javax.swing.JToolBar();
        cmdNuevo = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdAbrir = new javax.swing.JButton();
        cmdColor = new javax.swing.JButton();
        lblLapiz = new javax.swing.JLabel();
        cmbPinceles = new javax.swing.JComboBox<>();
        lblAreaDibujo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa Painter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtbBotones.setFloatable(false);
        jtbBotones.setRollover(true);

        cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entornos/programa4/imagenes/nuevo.png"))); // NOI18N
        cmdNuevo.setToolTipText("");
        cmdNuevo.setFocusable(false);
        cmdNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        jtbBotones.add(cmdNuevo);

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entornos/programa4/imagenes/guardar.png"))); // NOI18N
        cmdGuardar.setToolTipText("");
        cmdGuardar.setFocusable(false);
        cmdGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jtbBotones.add(cmdGuardar);

        cmdAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entornos/programa4/imagenes/abrir.png"))); // NOI18N
        cmdAbrir.setActionCommand("");
        cmdAbrir.setFocusable(false);
        cmdAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbrirActionPerformed(evt);
            }
        });
        jtbBotones.add(cmdAbrir);

        cmdColor.setBackground(new java.awt.Color(0, 0, 0));
        cmdColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entornos/programa4/imagenes/color.png"))); // NOI18N
        cmdColor.setFocusable(false);
        cmdColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdColorActionPerformed(evt);
            }
        });
        jtbBotones.add(cmdColor);

        lblLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/entornos/programa4/imagenes/lapiz.png"))); // NOI18N

        cmbPinceles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPincelesItemStateChanged(evt);
            }
        });

        lblAreaDibujo.setBackground(new java.awt.Color(0, 0, 0));
        lblAreaDibujo.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        lblAreaDibujo.setOpaque(true);
        lblAreaDibujo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblAreaDibujoMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtbBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(lblLapiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPinceles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(lblAreaDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtbBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLapiz, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cmbPinceles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAreaDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        lblLapiz.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Crea un nuevo lienzo del tamaño del área de dibujo.
    * Opcionalmente puede rellenarse con un color elegido por el usuario.
    */
   private void nuevaImagen(){
       // Inicializamos el lienzo del mismo tamaño que el área de dibujo
       lienzo = new BufferedImage(lblAreaDibujo.getWidth(),
                                  lblAreaDibujo.getHeight(),
                                  BufferedImage.TYPE_INT_RGB);


       // Rellenamos el fondo de blanco
        Graphics g = lienzo.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, lienzo.getWidth(), lienzo.getHeight());
        g.dispose();

        // Mostramos el lienzo en pantalla
        actualizarPantalla();
   }

    /**
     * Actualiza el contenido del JLabel de dibujo con la imagen actual.
     */
    private void actualizarPantalla() {
        Graphics g = lblAreaDibujo.getGraphics();
        g.drawImage(lienzo, 0, 0, null);
        g.dispose();
    }
    
    /**
    * Rellena el combo con los diferentes tipos de pinceles.
    */
   private void rellenarPinceles() {
       cmbPinceles.removeAllItems(); // limpiamos por si acaso

       cmbPinceles.addItem(new PincelBasico());
       cmbPinceles.addItem(new PincelContinuo());
       cmbPinceles.addItem(new PincelGordo());
       cmbPinceles.addItem(new PincelRectangulo());
       cmbPinceles.addItem(new PincelEstrella());
   }

   
    
    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        nuevaImagen();
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showSaveDialog(this);

        if(resultado == JFileChooser.APPROVE_OPTION){
            try{
                File archivo = selector.getSelectedFile();
                ImageIO.write(lienzo, "jpg", archivo);
                JOptionPane.showMessageDialog(this, "Imagen guardada correctamente.");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error al guardar la imagen: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbrirActionPerformed
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);

        if(resultado == JFileChooser.APPROVE_OPTION){
            try{
                File archivo = selector.getSelectedFile();
                lienzo = ImageIO.read(archivo);
                actualizarPantalla();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "No se pudo abrir la imagen: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmdAbrirActionPerformed

    private void cmdColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdColorActionPerformed
        //Abrimos el selector de colores
        Color colorElegido = JColorChooser.showDialog(this, "Elige un color", cmdColor.getBackground());

        //Si el usuario seleccionó un color (no canceló)
        if(colorElegido != null){
        //Cambiamos el color de fondo del botón
            cmdColor.setBackground(colorElegido);
        }
    }//GEN-LAST:event_cmdColorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        rellenarPinceles();
        nuevaImagen();
    }//GEN-LAST:event_formWindowOpened

    private void lblAreaDibujoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreaDibujoMouseDragged
        
        // Obtenemos el pincel seleccionado
        Pincel pincel = (Pincel)cmbPinceles.getSelectedItem();
        if(pincel == null) 
            return;

        // Obtenemos el Graphics del lienzo
        Graphics g = lienzo.getGraphics();

        // Color actual del botón cmdColor
        Color color = cmdColor.getBackground();
        g.setColor(color);

        // Obtenemos la posición del ratón
        Point punto = evt.getPoint();

        // Dibujamos usando el pincel
        pincel.dibujar(g, punto);

        g.dispose();
        actualizarPantalla();
        
    }//GEN-LAST:event_lblAreaDibujoMouseDragged

    private void cmbPincelesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPincelesItemStateChanged
        Pincel pincel = (Pincel) cmbPinceles.getSelectedItem();
        if(pincel != null) 
            pincel.resetear();
    }//GEN-LAST:event_cmbPincelesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDibujo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Pincel> cmbPinceles;
    private javax.swing.JButton cmdAbrir;
    private javax.swing.JButton cmdColor;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JToolBar jtbBotones;
    private javax.swing.JLabel lblAreaDibujo;
    private javax.swing.JLabel lblLapiz;
    // End of variables declaration//GEN-END:variables
}
